// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tradeview/accountplus/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AccountStateRequest is request type for the Query/AccountState RPC method.
type AccountStateRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *AccountStateRequest) Reset()         { *m = AccountStateRequest{} }
func (m *AccountStateRequest) String() string { return proto.CompactTextString(m) }
func (*AccountStateRequest) ProtoMessage()    {}
func (*AccountStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_076282bbe2c2096f, []int{0}
}
func (m *AccountStateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountStateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountStateRequest.Merge(m, src)
}
func (m *AccountStateRequest) XXX_Size() int {
	return m.Size()
}
func (m *AccountStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountStateRequest proto.InternalMessageInfo

func (m *AccountStateRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// AccountStateResponse is response type for the Query/GetAccountState RPC
// method.
type AccountStateResponse struct {
	AccountState *AccountState `protobuf:"bytes,1,opt,name=account_state,json=accountState,proto3" json:"account_state,omitempty"`
}

func (m *AccountStateResponse) Reset()         { *m = AccountStateResponse{} }
func (m *AccountStateResponse) String() string { return proto.CompactTextString(m) }
func (*AccountStateResponse) ProtoMessage()    {}
func (*AccountStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_076282bbe2c2096f, []int{1}
}
func (m *AccountStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountStateResponse.Merge(m, src)
}
func (m *AccountStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *AccountStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountStateResponse proto.InternalMessageInfo

func (m *AccountStateResponse) GetAccountState() *AccountState {
	if m != nil {
		return m.AccountState
	}
	return nil
}

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_076282bbe2c2096f, []int{2}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_076282bbe2c2096f, []int{3}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgGetAuthenticatorsRequest defines the Msg/GetAuthenticators request type.
type GetAuthenticatorsRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *GetAuthenticatorsRequest) Reset()         { *m = GetAuthenticatorsRequest{} }
func (m *GetAuthenticatorsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthenticatorsRequest) ProtoMessage()    {}
func (*GetAuthenticatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_076282bbe2c2096f, []int{4}
}
func (m *GetAuthenticatorsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAuthenticatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAuthenticatorsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAuthenticatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthenticatorsRequest.Merge(m, src)
}
func (m *GetAuthenticatorsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetAuthenticatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthenticatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthenticatorsRequest proto.InternalMessageInfo

func (m *GetAuthenticatorsRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// MsgGetAuthenticatorsResponse defines the Msg/GetAuthenticators response type.
type GetAuthenticatorsResponse struct {
	AccountAuthenticators []*AccountAuthenticator `protobuf:"bytes,1,rep,name=account_authenticators,json=accountAuthenticators,proto3" json:"account_authenticators,omitempty"`
}

func (m *GetAuthenticatorsResponse) Reset()         { *m = GetAuthenticatorsResponse{} }
func (m *GetAuthenticatorsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthenticatorsResponse) ProtoMessage()    {}
func (*GetAuthenticatorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_076282bbe2c2096f, []int{5}
}
func (m *GetAuthenticatorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAuthenticatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAuthenticatorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAuthenticatorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthenticatorsResponse.Merge(m, src)
}
func (m *GetAuthenticatorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetAuthenticatorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthenticatorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthenticatorsResponse proto.InternalMessageInfo

func (m *GetAuthenticatorsResponse) GetAccountAuthenticators() []*AccountAuthenticator {
	if m != nil {
		return m.AccountAuthenticators
	}
	return nil
}

// MsgGetAuthenticatorRequest defines the Msg/GetAuthenticator request type.
type GetAuthenticatorRequest struct {
	Account         string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AuthenticatorId uint64 `protobuf:"varint,2,opt,name=authenticator_id,json=authenticatorId,proto3" json:"authenticator_id,omitempty"`
}

func (m *GetAuthenticatorRequest) Reset()         { *m = GetAuthenticatorRequest{} }
func (m *GetAuthenticatorRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthenticatorRequest) ProtoMessage()    {}
func (*GetAuthenticatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_076282bbe2c2096f, []int{6}
}
func (m *GetAuthenticatorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAuthenticatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAuthenticatorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAuthenticatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthenticatorRequest.Merge(m, src)
}
func (m *GetAuthenticatorRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetAuthenticatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthenticatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthenticatorRequest proto.InternalMessageInfo

func (m *GetAuthenticatorRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetAuthenticatorRequest) GetAuthenticatorId() uint64 {
	if m != nil {
		return m.AuthenticatorId
	}
	return 0
}

// MsgGetAuthenticatorResponse defines the Msg/GetAuthenticator response type.
type GetAuthenticatorResponse struct {
	AccountAuthenticator *AccountAuthenticator `protobuf:"bytes,1,opt,name=account_authenticator,json=accountAuthenticator,proto3" json:"account_authenticator,omitempty"`
}

func (m *GetAuthenticatorResponse) Reset()         { *m = GetAuthenticatorResponse{} }
func (m *GetAuthenticatorResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthenticatorResponse) ProtoMessage()    {}
func (*GetAuthenticatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_076282bbe2c2096f, []int{7}
}
func (m *GetAuthenticatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetAuthenticatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetAuthenticatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetAuthenticatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthenticatorResponse.Merge(m, src)
}
func (m *GetAuthenticatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetAuthenticatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthenticatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthenticatorResponse proto.InternalMessageInfo

func (m *GetAuthenticatorResponse) GetAccountAuthenticator() *AccountAuthenticator {
	if m != nil {
		return m.AccountAuthenticator
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountStateRequest)(nil), "tradeview.accountplus.AccountStateRequest")
	proto.RegisterType((*AccountStateResponse)(nil), "tradeview.accountplus.AccountStateResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "tradeview.accountplus.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "tradeview.accountplus.QueryParamsResponse")
	proto.RegisterType((*GetAuthenticatorsRequest)(nil), "tradeview.accountplus.GetAuthenticatorsRequest")
	proto.RegisterType((*GetAuthenticatorsResponse)(nil), "tradeview.accountplus.GetAuthenticatorsResponse")
	proto.RegisterType((*GetAuthenticatorRequest)(nil), "tradeview.accountplus.GetAuthenticatorRequest")
	proto.RegisterType((*GetAuthenticatorResponse)(nil), "tradeview.accountplus.GetAuthenticatorResponse")
}

func init() { proto.RegisterFile("tradeview/accountplus/query.proto", fileDescriptor_076282bbe2c2096f) }

var fileDescriptor_076282bbe2c2096f = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xce, 0x95, 0x36, 0x88, 0x6b, 0x11, 0xe5, 0x9a, 0x40, 0x88, 0xa8, 0x1b, 0x0e, 0x21, 0xd2,
	0x56, 0xf8, 0x4a, 0xa8, 0x60, 0x40, 0x0c, 0x29, 0x03, 0x74, 0x03, 0x33, 0x20, 0x31, 0xd0, 0x5e,
	0xec, 0x53, 0x62, 0x29, 0xf1, 0xb9, 0xbe, 0x73, 0x69, 0x14, 0x22, 0x24, 0x06, 0x66, 0x24, 0x7e,
	0x00, 0x13, 0x33, 0xff, 0x80, 0xb9, 0x63, 0x25, 0x16, 0x26, 0x84, 0x12, 0x7e, 0x08, 0x8a, 0x7d,
	0x0d, 0x76, 0x62, 0xa7, 0xee, 0xe6, 0x7b, 0xef, 0x7b, 0xf7, 0xbe, 0xef, 0x7b, 0xe7, 0x07, 0x6f,
	0x49, 0x8f, 0x5a, 0xec, 0xd0, 0x66, 0xef, 0x08, 0x35, 0x4d, 0xee, 0x3b, 0xd2, 0x6d, 0xfb, 0x82,
	0x1c, 0xf8, 0xcc, 0xeb, 0xea, 0xae, 0xc7, 0x25, 0x47, 0xc5, 0x31, 0x44, 0x8f, 0x40, 0xca, 0x85,
	0x26, 0x6f, 0xf2, 0x00, 0x41, 0x46, 0x5f, 0x21, 0xb8, 0x7c, 0xb3, 0xc9, 0x79, 0xb3, 0xcd, 0x08,
	0x75, 0x6d, 0x42, 0x1d, 0x87, 0x4b, 0x2a, 0x6d, 0xee, 0x08, 0x95, 0xbd, 0x9b, 0xdc, 0x2d, 0xf2,
	0xad, 0x80, 0x38, 0x19, 0xd8, 0xe1, 0x16, 0x6b, 0x9f, 0x81, 0x71, 0xa9, 0x47, 0x3b, 0x0a, 0x83,
	0x09, 0x5c, 0xa9, 0x87, 0xb9, 0x57, 0x92, 0x4a, 0x66, 0xb0, 0x03, 0x9f, 0x09, 0x89, 0x4a, 0xf0,
	0x22, 0xb5, 0x2c, 0x8f, 0x09, 0x51, 0x02, 0x15, 0x50, 0xbd, 0x64, 0x9c, 0x1e, 0xf1, 0x3e, 0x2c,
	0xc4, 0x0b, 0x84, 0xcb, 0x1d, 0xc1, 0xd0, 0x73, 0x78, 0x59, 0x35, 0xd9, 0x13, 0xa3, 0x44, 0x50,
	0xb7, 0x58, 0xbb, 0xad, 0x27, 0x9a, 0xa3, 0xc7, 0xee, 0x58, 0xa2, 0x91, 0x13, 0x2e, 0x40, 0xf4,
	0x72, 0xe4, 0xee, 0x8b, 0x80, 0xa7, 0x62, 0x84, 0x0d, 0xb8, 0x12, 0x8b, 0xaa, 0xb6, 0x8f, 0x61,
	0x3e, 0xd4, 0xa3, 0xfa, 0xad, 0xa6, 0xf4, 0x0b, 0xcb, 0x76, 0xe6, 0x8f, 0x7f, 0xaf, 0xe5, 0x0c,
	0x55, 0x82, 0xb7, 0x61, 0xe9, 0x19, 0x93, 0x75, 0x5f, 0xb6, 0x98, 0x23, 0x6d, 0x93, 0x4a, 0xee,
	0x89, 0xa8, 0x03, 0x61, 0xfd, 0xd8, 0x81, 0xf0, 0x88, 0x3f, 0xc0, 0x1b, 0x09, 0x55, 0x8a, 0x4f,
	0x03, 0x5e, 0x3b, 0xb5, 0x81, 0xc6, 0x10, 0x25, 0x50, 0xb9, 0x50, 0x5d, 0xac, 0x6d, 0xce, 0xf6,
	0x23, 0x76, 0xab, 0x51, 0xa4, 0x09, 0x51, 0x81, 0xdf, 0xc2, 0xeb, 0x93, 0x04, 0xce, 0x64, 0x8d,
	0xd6, 0xe1, 0x72, 0x8c, 0xd0, 0x9e, 0x6d, 0x95, 0xe6, 0x2a, 0xa0, 0x3a, 0x6f, 0x5c, 0x89, 0xc5,
	0x77, 0x2d, 0xfc, 0x7e, 0xda, 0x96, 0xb1, 0xbe, 0x7d, 0x58, 0x4c, 0xd4, 0xa7, 0xec, 0x3f, 0x97,
	0xbc, 0x42, 0x92, 0xbc, 0xda, 0xb7, 0x05, 0xb8, 0x10, 0x4c, 0x1a, 0x7d, 0x02, 0x30, 0x1f, 0xce,
	0x0d, 0xad, 0xa7, 0xdc, 0x3b, 0xfd, 0x50, 0xca, 0x1b, 0x59, 0xa0, 0xa1, 0x1a, 0x7c, 0xe7, 0xe3,
	0xcf, 0xbf, 0x5f, 0xe6, 0xd6, 0xd0, 0x2a, 0x99, 0xf5, 0xab, 0xa0, 0x1f, 0x00, 0x2e, 0x4f, 0x3a,
	0x82, 0xf4, 0x94, 0x3e, 0x29, 0xa3, 0x29, 0x93, 0xcc, 0x78, 0x45, 0x6e, 0x37, 0x20, 0xf7, 0x14,
	0xd5, 0x53, 0xc8, 0xc5, 0xfc, 0x27, 0x3d, 0x95, 0xea, 0x93, 0xde, 0xe4, 0x9c, 0xfb, 0xe8, 0x3b,
	0x80, 0x57, 0xa7, 0xde, 0x2c, 0xca, 0xca, 0x68, 0x6c, 0xed, 0x56, 0xf6, 0x02, 0xa5, 0xe1, 0x51,
	0xa0, 0xe1, 0x3e, 0x22, 0x59, 0x34, 0x88, 0xff, 0x22, 0xd0, 0x57, 0x00, 0x97, 0xa2, 0x3b, 0x02,
	0x6d, 0x64, 0x59, 0x24, 0x8a, 0xe7, 0x66, 0x26, 0xac, 0xa2, 0xf8, 0x30, 0xa0, 0xb8, 0x85, 0x74,
	0x32, 0x73, 0xf7, 0x86, 0x5b, 0x8d, 0xf4, 0xd4, 0x1e, 0xec, 0xef, 0xbc, 0x3e, 0x1e, 0x68, 0xe0,
	0x64, 0xa0, 0x81, 0x3f, 0x03, 0x0d, 0x7c, 0x1e, 0x6a, 0xb9, 0x93, 0xa1, 0x96, 0xfb, 0x35, 0xd4,
	0x72, 0x6f, 0x9e, 0x34, 0x6d, 0xd9, 0xf2, 0x1b, 0xba, 0xc9, 0x3b, 0xc4, 0xea, 0x5a, 0x47, 0xc1,
	0xa6, 0x35, 0x79, 0x9b, 0x1c, 0x6e, 0xdf, 0x33, 0x5b, 0xd4, 0x76, 0xc8, 0x38, 0x72, 0x14, 0x6b,
	0x25, 0xbb, 0x2e, 0x13, 0x8d, 0x7c, 0x90, 0x7d, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x9f,
	0xf8, 0x46, 0x7a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a single authenticator by account and authenticator ID.
	GetAuthenticator(ctx context.Context, in *GetAuthenticatorRequest, opts ...grpc.CallOption) (*GetAuthenticatorResponse, error)
	// Queries all authenticators for a given account.
	GetAuthenticators(ctx context.Context, in *GetAuthenticatorsRequest, opts ...grpc.CallOption) (*GetAuthenticatorsResponse, error)
	// Queries for an account state (timestamp nonce).
	AccountState(ctx context.Context, in *AccountStateRequest, opts ...grpc.CallOption) (*AccountStateResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/tradeview.accountplus.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAuthenticator(ctx context.Context, in *GetAuthenticatorRequest, opts ...grpc.CallOption) (*GetAuthenticatorResponse, error) {
	out := new(GetAuthenticatorResponse)
	err := c.cc.Invoke(ctx, "/tradeview.accountplus.Query/GetAuthenticator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAuthenticators(ctx context.Context, in *GetAuthenticatorsRequest, opts ...grpc.CallOption) (*GetAuthenticatorsResponse, error) {
	out := new(GetAuthenticatorsResponse)
	err := c.cc.Invoke(ctx, "/tradeview.accountplus.Query/GetAuthenticators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AccountState(ctx context.Context, in *AccountStateRequest, opts ...grpc.CallOption) (*AccountStateResponse, error) {
	out := new(AccountStateResponse)
	err := c.cc.Invoke(ctx, "/tradeview.accountplus.Query/AccountState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a single authenticator by account and authenticator ID.
	GetAuthenticator(context.Context, *GetAuthenticatorRequest) (*GetAuthenticatorResponse, error)
	// Queries all authenticators for a given account.
	GetAuthenticators(context.Context, *GetAuthenticatorsRequest) (*GetAuthenticatorsResponse, error)
	// Queries for an account state (timestamp nonce).
	AccountState(context.Context, *AccountStateRequest) (*AccountStateResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetAuthenticator(ctx context.Context, req *GetAuthenticatorRequest) (*GetAuthenticatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthenticator not implemented")
}
func (*UnimplementedQueryServer) GetAuthenticators(ctx context.Context, req *GetAuthenticatorsRequest) (*GetAuthenticatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthenticators not implemented")
}
func (*UnimplementedQueryServer) AccountState(ctx context.Context, req *AccountStateRequest) (*AccountStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountState not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeview.accountplus.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAuthenticator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthenticatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAuthenticator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeview.accountplus.Query/GetAuthenticator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAuthenticator(ctx, req.(*GetAuthenticatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAuthenticators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthenticatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAuthenticators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeview.accountplus.Query/GetAuthenticators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAuthenticators(ctx, req.(*GetAuthenticatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AccountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AccountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeview.accountplus.Query/AccountState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AccountState(ctx, req.(*AccountStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tradeview.accountplus.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetAuthenticator",
			Handler:    _Query_GetAuthenticator_Handler,
		},
		{
			MethodName: "GetAuthenticators",
			Handler:    _Query_GetAuthenticators_Handler,
		},
		{
			MethodName: "AccountState",
			Handler:    _Query_AccountState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tradeview/accountplus/query.proto",
}

func (m *AccountStateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountStateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountStateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AccountStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AccountState != nil {
		{
			size, err := m.AccountState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *GetAuthenticatorsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAuthenticatorsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAuthenticatorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetAuthenticatorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAuthenticatorsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAuthenticatorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccountAuthenticators) > 0 {
		for iNdEx := len(m.AccountAuthenticators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccountAuthenticators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetAuthenticatorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAuthenticatorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAuthenticatorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AuthenticatorId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AuthenticatorId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetAuthenticatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetAuthenticatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetAuthenticatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AccountAuthenticator != nil {
		{
			size, err := m.AccountAuthenticator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AccountStateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *AccountStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AccountState != nil {
		l = m.AccountState.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *GetAuthenticatorsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetAuthenticatorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AccountAuthenticators) > 0 {
		for _, e := range m.AccountAuthenticators {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *GetAuthenticatorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AuthenticatorId != 0 {
		n += 1 + sovQuery(uint64(m.AuthenticatorId))
	}
	return n
}

func (m *GetAuthenticatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AccountAuthenticator != nil {
		l = m.AccountAuthenticator.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AccountStateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountStateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountStateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AccountState == nil {
				m.AccountState = &AccountState{}
			}
			if err := m.AccountState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAuthenticatorsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAuthenticatorsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAuthenticatorsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAuthenticatorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAuthenticatorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAuthenticatorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAuthenticators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountAuthenticators = append(m.AccountAuthenticators, &AccountAuthenticator{})
			if err := m.AccountAuthenticators[len(m.AccountAuthenticators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAuthenticatorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAuthenticatorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAuthenticatorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthenticatorId", wireType)
			}
			m.AuthenticatorId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuthenticatorId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetAuthenticatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetAuthenticatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetAuthenticatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAuthenticator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AccountAuthenticator == nil {
				m.AccountAuthenticator = &AccountAuthenticator{}
			}
			if err := m.AccountAuthenticator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
