// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	"github.com/cosmos/cosmos-sdk/baseapp"
	sdk "github.com/cosmos/cosmos-sdk/types"
	mock "github.com/stretchr/testify/mock"
)

// MsgRouter is an autogenerated mock type for the MsgRouter type
type MsgRouter struct {
	mock.Mock
}

// Handler provides a mock function with given fields: msg
func (_m *MsgRouter) Handler(msg sdk.Msg) baseapp.MsgServiceHandler {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Handler")
	}

	var r0 baseapp.MsgServiceHandler
	if rf, ok := ret.Get(0).(func(sdk.Msg) baseapp.MsgServiceHandler); ok {
		r0 = rf(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(baseapp.MsgServiceHandler)
		}
	}

	return r0
}

// NewMsgRouter creates a new instance of MsgRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMsgRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MsgRouter {
	mock := &MsgRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
